### ISSUE TITLE
Setting up

### ISSUE THREAD

**Issue by BlueWGT** [Loli-Killer/ArknightsCrisisSimulator#2]
Hi, I wanted to get this set up and had no problems setting up the proxy and directing the emulator's https, but the batch file doesn't seem to do anything. The instructions aren't clear as to what is supposed to pop up, I'd assume a python UI. Any easy troubleshoots? The emulator is Mumu on marshmallow.

**Comment by Loli-Killer** [comment]
These things should pop up.

Easy troubleshooting maybe editing the the `start.bat` and adding a `pause` to the end of the file in a new line which will make the script to not exit immediately which may let you see what the error is.

![image](https://user-images.githubusercontent.com/38392948/169698086-c2518cfe-8b2f-40a6-8457-0461e7706d46.png)
![image](https://user-images.githubusercontent.com/38392948/169698095-385089b7-7272-4f08-9474-c4bbd522848c.png)

**Comment by BlueWGT** [comment]
I got it all fixed and both mods work flawlessly, thank you! Just curious, how safe do you think the CC mod is? I would consider using it on my main if this smurf account survives a few months.

**Comment by Loli-Killer** [comment]
Personally I think it's safe to use since my mod doesn't report back to server and it's all client-sided. Although am not sure what you meant by "both" mods. All it does is change the http response it receives from the server. I haven't been using it much lately since I am waiting for CC#7 to make new changes but I debugged all the CC I've updated before using my main account and still haven't been banned so. You can read more on the "How it works" section in the readme.

**Comment by Loli-Killer** [comment]
Although I haven't been banned yet and can't see any reason how they will detect it, I cannot 100% guarantee you that you cannot be banned since I don't work at hypergyrph so, do use this at your own risk.

**Comment by BlueWGT** [comment]
Both was referring to your other mod ArknightsBattleSimulator.

**Comment by Loli-Killer** [comment]
Oh, both mods work by modifying http esponse without sending back the modified data back to actual server so it should be pretty safe. But again can't 100% guarantee there won't be any ban although I haven't seen any bans yet.
